"""Data models for CSAF VEX."""

from csaf_lib.models.common import Acknowledgment, Note, Reference
from csaf_lib.models.csafvex import CSAFVEX
from csaf_lib.models.document import (
    TLP,
    AggregateSeverity,
    Distribution,
    Document,
    Engine,
    Generator,
    Publisher,
    Revision,
    Tracking,
)
from csaf_lib.models.enums import (
    BranchCategory,
    CSAFVersion,
    FlagLabel,
    InvolvementParty,
    InvolvementStatus,
    NoteCategory,
    PublisherCategory,
    ReferenceCategory,
    RelationshipCategory,
    RemediationCategory,
    RestartCategory,
    ThreatCategory,
    TLPLabel,
    TrackingStatus,
)
from csaf_lib.models.product_tree import (
    Branch,
    FullProductName,
    ProductIdentificationHelper,
    ProductTree,
    Relationship,
)
from csaf_lib.models.vulnerability import (
    CWE,
    ID,
    Flag,
    Involvement,
    ProductStatus,
    Remediation,
    RestartRequired,
    Score,
    Threat,
    Vulnerability,
)

__all__ = [
    "CSAFVEX",
    "CWE",
    "ID",
    "TLP",
    "Acknowledgment",
    "AggregateSeverity",
    "Branch",
    "BranchCategory",
    "CSAFVersion",
    "Distribution",
    "Document",
    "Engine",
    "Flag",
    "FlagLabel",
    "FullProductName",
    "Generator",
    "Involvement",
    "InvolvementParty",
    "InvolvementStatus",
    "Note",
    "NoteCategory",
    "ProductIdentificationHelper",
    "ProductStatus",
    "ProductTree",
    "Publisher",
    "PublisherCategory",
    "Reference",
    "ReferenceCategory",
    "Relationship",
    "RelationshipCategory",
    "Remediation",
    "RemediationCategory",
    "RestartCategory",
    "RestartRequired",
    "Revision",
    "Score",
    "TLPLabel",
    "Threat",
    "ThreatCategory",
    "Tracking",
    "TrackingStatus",
    "Vulnerability",
]
